### ISSUE TITLE
error when running build.sh

### ISSUE THREAD

**Issue by niryariv** [Gizra/public_education#101]
getting this every time im running build.sh (tested on a clean git clone):

```
 Elapsed time
    coffee       30ms
    coffee:dist  31ms
    coffee:test  8ms
    Total        69ms
        Warning:
    /Users/niryariv/Projects/public_education/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
      throw err;
            ^
    Error: spawn ENOENT
        at errnoException (child_process.js:980:11)
        at Process.ChildProcess._handle.onexit (child_process.js:771:34) Use --force to continue.

        Aborted due to warnings.

        Elapsed time
```

**Comment by amitaibu** [comment]
It's only on your system, Try to re-install compass/ sass
