### ISSUE TITLE
Latest pull breaks with errors

### ISSUE THREAD

**Issue by mushon** [Gizra/public_education#143]
After pulling from master and running `grunt server` the page is borked with main.js and main.css unfound:

```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:9000/styles/main.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:9000/scripts/controllers/main.js
Error: Argument 'ListMarkersCtrl' is not a function, got undefined
    at assertArg (http://localhost:9000/bower_components/angular/angular.js:1099:11)
    at assertArgFn (http://localhost:9000/bower_components/angular/angular.js:1109:3)
    at http://localhost:9000/bower_components/angular/angular.js:4978:9
    at update (http://localhost:9000/bower_components/angular/angular.js:14509:26)
    at Object.Scope.$broadcast (http://localhost:9000/bower_components/angular/angular.js:8468:28)
    at http://localhost:9000/bower_components/angular/angular.js:7614:26
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:6995:59)
    at wrappedCallback (http://localhost:9000/bower_components/angular/angular.js:6995:59)
    at http://localhost:9000/bower_components/angular/angular.js:7032:26
    at Object.Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:8218:28) angular.js:5930

```

![screen shot 2013-11-05 at 6 56 58 am](https://f.cloud.github.com/assets/27123/1471149/d202c604-45d6-11e3-804c-3840b5ba5c5f.png)

Please fix asap, as right now I cannot work on the design.

**Comment by mushon** [comment]
I see the same problem in the `gh-pages` branch

**Comment by amitaibu** [comment]
I believe it's on your system, as I'm not seeing any errors on my local + on http://pe.mushon.com/#/ (if you do see on pe.mushon, please attach screenshot of the exact state you are)

Please confirm:
- You are on a clean master (`git pull && git reset --hard origin/master`)
- executed `npm install && bower install`
- Your config.json is updated according to the provided gist sent by mail some time ago

**Comment by amitaibu** [comment]
Maybe related to #145 ?

**Comment by amitaibu** [comment]
Please `git pull && bower update`

**Comment by mushon** [comment]
Ok, fixed. @bricel and I were trying to fix something else tomorrow and we copied `gruntfile.js` instead of `config.json`. It's running now (in my hotel room in Istanbul)
