### ISSUE TITLE
Stop the sound when press close button  

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/public_education#46]
When the recording of the marker is playing, and press close button the sound have to stop before back.

**Comment by ceoaliongroo** [comment]
Need to have a test in iOS work in Android

**Comment by ceoaliongroo** [comment]
On web: work ok!
On android: work ok!
On iphone: Application close when call stop action

XCode Error mssage:
2013-10-31 14:23:14.341 PublicEducation[2056:60b] THREAD WARNING: ['Media'] took '87.382080' ms. Plugin should use a background thread.
2013-10-31 14:23:18.141 PublicEducation[2056:60b] Stopped playing audio sample 'https://s3.amazonaws.com/PE-dev/1383221419329.wav'
2013-10-31 14:23:28.192 PublicEducation[2056:4703] void SendDelegateMessage(NSInvocation *): delegate (webView:saveStateToHistoryItem:forFrame:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode

**Comment by amitaibu** [comment]
@ceoaliongroo check what happens if you call stop twice on the same Media object. I have a feeling you will need to also check if Media is actually playing.

Also, what happens if you just `Media = null`?

**Comment by ceoaliongroo** [comment]
Work in both devices - but still have this error

Error: $digest already in progress angular.js:8494
processMessage failed: Message: Jcordova.require('org.apache.cordova.media.Media').onStatus('456e41f1-71f3-460b-ca00-1c78e3a5acdd', 1, 1); cordova.js:1031
processMessage failed: Error: Error: $digest already in progress cordova.js:1032
processMessage failed: Stack: Error: $digest already in progress
    at Error (unknown source)
    at beginPhase (content://jsHybugger.org/file:///android_asset/www/bower_components/angular/angular.js:16933:7)
    at Object.$get.Scope.$digest (content://jsHybugger.org/file:///android_asset/www/bower_components/angular/angular.js:16429:1)
    at onStatus [as statusCallback](content://jsHybugger.org/file:///android_asset/www/scripts/90804411.scripts.js:2664:12)
    at Function.Media.onStatus (content://jsHybugger.org/file:///android_asset/www/plugins/org.apache.cordova.media/www/Media.js:436:31)
    at eval (eval at processMessage (content://jsHybugger.org/file:///android_asset/www/cordova.js:2516:17))
    at processMessage (content://jsHybugger.org/file:///android_asset/www/cordova.js:2516:1)
    at Function.androidExec.processMessages (content://jsHybugger.org/file:///android_asset/www/cordova.js:2681:1)
    at androidExec (content://jsHybugger.org/file:///android_asset/www/cordova.js:2265:13)
    at Media.play (content://jsHybugger.org/file:///android_asset/www/plugins/org.apache.cordova.media/www/Media.js:115:1) cordova.js:1033
2
