### ISSUE TITLE
Fail compile for android on phonegap android after remove config.xml

### ISSUE THREAD

**Issue by ceoaliongroo** [Gizra/public_education#73]
[phonegap] detecting Android SDK environment...
[phonegap] using the local environment
[phonegap] compiling Android...

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/home/carlos/development/public_education/www/config.xml'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Object.module.exports.parseElementtreeSync (/usr/lib/node_modules/phonegap/node_modules/cordova/src/xml-helpers.js:107:27)
    at Object.config_parser (/usr/lib/node_modules/phonegap/node_modules/cordova/src/config_parser.js:25:20)
    at /usr/lib/node_modules/phonegap/node_modules/cordova/src/prepare.js:67:23
    at /usr/lib/node_modules/phonegap/node_modules/cordova/src/hooker.js:67:25
    at execute_scripts_serially (/usr/lib/node_modules/phonegap/node_modules/cordova/src/hooker.js:94:9)
    at /usr/lib/node_modules/phonegap/node_modules/cordova/src/hooker.js:63:17
    at execute_handlers_serially (/usr/lib/node_modules/phonegap/node_modules/cordova/src/hooker.js:110:9)
    at Object.fire (/usr/lib/node_modules/phonegap/node_modules/cordova/src/hooker.js:55:9)

**Comment by amitaibu** [comment]
Why remove config.xml? It should remain in the repo

**Comment by ceoaliongroo** [comment]
Yes, thanks  
Fixed in PR #72
